name: Linux Monitoring CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bash-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Bash syntax
        run: bash -n scripts/system_health.sh

      - name: Check monitoring configuration
        run: bash -n config/monitoring.conf
